package com.sinosoft.planb.db.entity;

import java.util.Date;

public class OutPlan {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column outplan.serialno
     *
     * @mbggenerated Tue May 30 13:30:43 CST 2017
     */
    private Integer serialNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column outplan.year
     *
     * @mbggenerated Tue May 30 13:30:43 CST 2017
     */
    private String year;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column outplan.quarter
     *
     * @mbggenerated Tue May 30 13:30:43 CST 2017
     */
    private String quarter;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column outplan.modular
     *
     * @mbggenerated Tue May 30 13:30:43 CST 2017
     */
    private String modular;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column outplan.oa
     *
     * @mbggenerated Tue May 30 13:30:43 CST 2017
     */
    private String oa;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column outplan.seq
     *
     * @mbggenerated Tue May 30 13:30:43 CST 2017
     */
    private String seq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column outplan.seqname
     *
     * @mbggenerated Tue May 30 13:30:43 CST 2017
     */
    private String seqName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column outplan.analyst
     *
     * @mbggenerated Tue May 30 13:30:43 CST 2017
     */
    private String analyst;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column outplan.analystart
     *
     * @mbggenerated Tue May 30 13:30:43 CST 2017
     */
    private Date analyStart;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column outplan.analyend
     *
     * @mbggenerated Tue May 30 13:30:43 CST 2017
     */
    private Date analyEnd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column outplan.developer
     *
     * @mbggenerated Tue May 30 13:30:43 CST 2017
     */
    private String developer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column outplan.developerstart
     *
     * @mbggenerated Tue May 30 13:30:43 CST 2017
     */
    private Date developerStart;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column outplan.developerend
     *
     * @mbggenerated Tue May 30 13:30:43 CST 2017
     */
    private Date developerEnd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column outplan.changeflag
     *
     * @mbggenerated Tue May 30 13:30:43 CST 2017
     */
    private String changeFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column outplan.remark
     *
     * @mbggenerated Tue May 30 13:30:43 CST 2017
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column outplan.operator
     *
     * @mbggenerated Tue May 30 13:30:43 CST 2017
     */
    private String operator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column outplan.changedate
     *
     * @mbggenerated Tue May 30 13:30:43 CST 2017
     */
    private Date changeDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column outplan.serialno
     *
     * @return the value of outplan.serialno
     *
     * @mbggenerated Tue May 30 13:30:43 CST 2017
     */
    public Integer getSerialNo() {
        return serialNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column outplan.serialno
     *
     * @param serialNo the value for outplan.serialno
     *
     * @mbggenerated Tue May 30 13:30:43 CST 2017
     */
    public void setSerialNo(Integer serialNo) {
        this.serialNo = serialNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column outplan.year
     *
     * @return the value of outplan.year
     *
     * @mbggenerated Tue May 30 13:30:43 CST 2017
     */
    public String getYear() {
        return year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column outplan.year
     *
     * @param year the value for outplan.year
     *
     * @mbggenerated Tue May 30 13:30:43 CST 2017
     */
    public void setYear(String year) {
        this.year = year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column outplan.quarter
     *
     * @return the value of outplan.quarter
     *
     * @mbggenerated Tue May 30 13:30:43 CST 2017
     */
    public String getQuarter() {
        return quarter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column outplan.quarter
     *
     * @param quarter the value for outplan.quarter
     *
     * @mbggenerated Tue May 30 13:30:43 CST 2017
     */
    public void setQuarter(String quarter) {
        this.quarter = quarter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column outplan.modular
     *
     * @return the value of outplan.modular
     *
     * @mbggenerated Tue May 30 13:30:43 CST 2017
     */
    public String getModular() {
        return modular;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column outplan.modular
     *
     * @param modular the value for outplan.modular
     *
     * @mbggenerated Tue May 30 13:30:43 CST 2017
     */
    public void setModular(String modular) {
        this.modular = modular;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column outplan.oa
     *
     * @return the value of outplan.oa
     *
     * @mbggenerated Tue May 30 13:30:43 CST 2017
     */
    public String getOa() {
        return oa;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column outplan.oa
     *
     * @param oa the value for outplan.oa
     *
     * @mbggenerated Tue May 30 13:30:43 CST 2017
     */
    public void setOa(String oa) {
        this.oa = oa;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column outplan.seq
     *
     * @return the value of outplan.seq
     *
     * @mbggenerated Tue May 30 13:30:43 CST 2017
     */
    public String getSeq() {
        return seq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column outplan.seq
     *
     * @param seq the value for outplan.seq
     *
     * @mbggenerated Tue May 30 13:30:43 CST 2017
     */
    public void setSeq(String seq) {
        this.seq = seq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column outplan.seqname
     *
     * @return the value of outplan.seqname
     *
     * @mbggenerated Tue May 30 13:30:43 CST 2017
     */
    public String getSeqName() {
        return seqName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column outplan.seqname
     *
     * @param seqName the value for outplan.seqname
     *
     * @mbggenerated Tue May 30 13:30:43 CST 2017
     */
    public void setSeqName(String seqName) {
        this.seqName = seqName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column outplan.analyst
     *
     * @return the value of outplan.analyst
     *
     * @mbggenerated Tue May 30 13:30:43 CST 2017
     */
    public String getAnalyst() {
        return analyst;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column outplan.analyst
     *
     * @param analyst the value for outplan.analyst
     *
     * @mbggenerated Tue May 30 13:30:43 CST 2017
     */
    public void setAnalyst(String analyst) {
        this.analyst = analyst;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column outplan.analystart
     *
     * @return the value of outplan.analystart
     *
     * @mbggenerated Tue May 30 13:30:43 CST 2017
     */
    public Date getAnalyStart() {
        return analyStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column outplan.analystart
     *
     * @param analyStart the value for outplan.analystart
     *
     * @mbggenerated Tue May 30 13:30:43 CST 2017
     */
    public void setAnalyStart(Date analyStart) {
        this.analyStart = analyStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column outplan.analyend
     *
     * @return the value of outplan.analyend
     *
     * @mbggenerated Tue May 30 13:30:43 CST 2017
     */
    public Date getAnalyEnd() {
        return analyEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column outplan.analyend
     *
     * @param analyEnd the value for outplan.analyend
     *
     * @mbggenerated Tue May 30 13:30:43 CST 2017
     */
    public void setAnalyEnd(Date analyEnd) {
        this.analyEnd = analyEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column outplan.developer
     *
     * @return the value of outplan.developer
     *
     * @mbggenerated Tue May 30 13:30:43 CST 2017
     */
    public String getDeveloper() {
        return developer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column outplan.developer
     *
     * @param developer the value for outplan.developer
     *
     * @mbggenerated Tue May 30 13:30:43 CST 2017
     */
    public void setDeveloper(String developer) {
        this.developer = developer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column outplan.developerstart
     *
     * @return the value of outplan.developerstart
     *
     * @mbggenerated Tue May 30 13:30:43 CST 2017
     */
    public Date getDeveloperStart() {
        return developerStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column outplan.developerstart
     *
     * @param developerStart the value for outplan.developerstart
     *
     * @mbggenerated Tue May 30 13:30:43 CST 2017
     */
    public void setDeveloperStart(Date developerStart) {
        this.developerStart = developerStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column outplan.developerend
     *
     * @return the value of outplan.developerend
     *
     * @mbggenerated Tue May 30 13:30:43 CST 2017
     */
    public Date getDeveloperEnd() {
        return developerEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column outplan.developerend
     *
     * @param developerEnd the value for outplan.developerend
     *
     * @mbggenerated Tue May 30 13:30:43 CST 2017
     */
    public void setDeveloperEnd(Date developerEnd) {
        this.developerEnd = developerEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column outplan.changeflag
     *
     * @return the value of outplan.changeflag
     *
     * @mbggenerated Tue May 30 13:30:43 CST 2017
     */
    public String getChangeFlag() {
        return changeFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column outplan.changeflag
     *
     * @param changeFlag the value for outplan.changeflag
     *
     * @mbggenerated Tue May 30 13:30:43 CST 2017
     */
    public void setChangeFlag(String changeFlag) {
        this.changeFlag = changeFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column outplan.remark
     *
     * @return the value of outplan.remark
     *
     * @mbggenerated Tue May 30 13:30:43 CST 2017
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column outplan.remark
     *
     * @param remark the value for outplan.remark
     *
     * @mbggenerated Tue May 30 13:30:43 CST 2017
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column outplan.operator
     *
     * @return the value of outplan.operator
     *
     * @mbggenerated Tue May 30 13:30:43 CST 2017
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column outplan.operator
     *
     * @param operator the value for outplan.operator
     *
     * @mbggenerated Tue May 30 13:30:43 CST 2017
     */
    public void setOperator(String operator) {
        this.operator = operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column outplan.changedate
     *
     * @return the value of outplan.changedate
     *
     * @mbggenerated Tue May 30 13:30:43 CST 2017
     */
    public Date getChangeDate() {
        return changeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column outplan.changedate
     *
     * @param changeDate the value for outplan.changedate
     *
     * @mbggenerated Tue May 30 13:30:43 CST 2017
     */
    public void setChangeDate(Date changeDate) {
        this.changeDate = changeDate;
    }
}