package com.sinosoft.planb.db.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class OutPlanExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table outplan
     *
     * @mbggenerated Tue May 30 13:30:43 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table outplan
     *
     * @mbggenerated Tue May 30 13:30:43 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table outplan
     *
     * @mbggenerated Tue May 30 13:30:43 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outplan
     *
     * @mbggenerated Tue May 30 13:30:43 CST 2017
     */
    public OutPlanExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outplan
     *
     * @mbggenerated Tue May 30 13:30:43 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outplan
     *
     * @mbggenerated Tue May 30 13:30:43 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outplan
     *
     * @mbggenerated Tue May 30 13:30:43 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outplan
     *
     * @mbggenerated Tue May 30 13:30:43 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outplan
     *
     * @mbggenerated Tue May 30 13:30:43 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outplan
     *
     * @mbggenerated Tue May 30 13:30:43 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outplan
     *
     * @mbggenerated Tue May 30 13:30:43 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outplan
     *
     * @mbggenerated Tue May 30 13:30:43 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outplan
     *
     * @mbggenerated Tue May 30 13:30:43 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outplan
     *
     * @mbggenerated Tue May 30 13:30:43 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table outplan
     *
     * @mbggenerated Tue May 30 13:30:43 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andSerialNoIsNull() {
            addCriterion("serialno is null");
            return (Criteria) this;
        }

        public Criteria andSerialNoIsNotNull() {
            addCriterion("serialno is not null");
            return (Criteria) this;
        }

        public Criteria andSerialNoEqualTo(Integer value) {
            addCriterion("serialno =", value, "serialNo");
            return (Criteria) this;
        }

        public Criteria andSerialNoNotEqualTo(Integer value) {
            addCriterion("serialno <>", value, "serialNo");
            return (Criteria) this;
        }

        public Criteria andSerialNoGreaterThan(Integer value) {
            addCriterion("serialno >", value, "serialNo");
            return (Criteria) this;
        }

        public Criteria andSerialNoGreaterThanOrEqualTo(Integer value) {
            addCriterion("serialno >=", value, "serialNo");
            return (Criteria) this;
        }

        public Criteria andSerialNoLessThan(Integer value) {
            addCriterion("serialno <", value, "serialNo");
            return (Criteria) this;
        }

        public Criteria andSerialNoLessThanOrEqualTo(Integer value) {
            addCriterion("serialno <=", value, "serialNo");
            return (Criteria) this;
        }

        public Criteria andSerialNoIn(List<Integer> values) {
            addCriterion("serialno in", values, "serialNo");
            return (Criteria) this;
        }

        public Criteria andSerialNoNotIn(List<Integer> values) {
            addCriterion("serialno not in", values, "serialNo");
            return (Criteria) this;
        }

        public Criteria andSerialNoBetween(Integer value1, Integer value2) {
            addCriterion("serialno between", value1, value2, "serialNo");
            return (Criteria) this;
        }

        public Criteria andSerialNoNotBetween(Integer value1, Integer value2) {
            addCriterion("serialno not between", value1, value2, "serialNo");
            return (Criteria) this;
        }

        public Criteria andYearIsNull() {
            addCriterion("year is null");
            return (Criteria) this;
        }

        public Criteria andYearIsNotNull() {
            addCriterion("year is not null");
            return (Criteria) this;
        }

        public Criteria andYearEqualTo(String value) {
            addCriterion("year =", value, "year");
            return (Criteria) this;
        }

        public Criteria andYearNotEqualTo(String value) {
            addCriterion("year <>", value, "year");
            return (Criteria) this;
        }

        public Criteria andYearGreaterThan(String value) {
            addCriterion("year >", value, "year");
            return (Criteria) this;
        }

        public Criteria andYearGreaterThanOrEqualTo(String value) {
            addCriterion("year >=", value, "year");
            return (Criteria) this;
        }

        public Criteria andYearLessThan(String value) {
            addCriterion("year <", value, "year");
            return (Criteria) this;
        }

        public Criteria andYearLessThanOrEqualTo(String value) {
            addCriterion("year <=", value, "year");
            return (Criteria) this;
        }

        public Criteria andYearLike(String value) {
            addCriterion("year like", value, "year");
            return (Criteria) this;
        }

        public Criteria andYearNotLike(String value) {
            addCriterion("year not like", value, "year");
            return (Criteria) this;
        }

        public Criteria andYearIn(List<String> values) {
            addCriterion("year in", values, "year");
            return (Criteria) this;
        }

        public Criteria andYearNotIn(List<String> values) {
            addCriterion("year not in", values, "year");
            return (Criteria) this;
        }

        public Criteria andYearBetween(String value1, String value2) {
            addCriterion("year between", value1, value2, "year");
            return (Criteria) this;
        }

        public Criteria andYearNotBetween(String value1, String value2) {
            addCriterion("year not between", value1, value2, "year");
            return (Criteria) this;
        }

        public Criteria andQuarterIsNull() {
            addCriterion("quarter is null");
            return (Criteria) this;
        }

        public Criteria andQuarterIsNotNull() {
            addCriterion("quarter is not null");
            return (Criteria) this;
        }

        public Criteria andQuarterEqualTo(String value) {
            addCriterion("quarter =", value, "quarter");
            return (Criteria) this;
        }

        public Criteria andQuarterNotEqualTo(String value) {
            addCriterion("quarter <>", value, "quarter");
            return (Criteria) this;
        }

        public Criteria andQuarterGreaterThan(String value) {
            addCriterion("quarter >", value, "quarter");
            return (Criteria) this;
        }

        public Criteria andQuarterGreaterThanOrEqualTo(String value) {
            addCriterion("quarter >=", value, "quarter");
            return (Criteria) this;
        }

        public Criteria andQuarterLessThan(String value) {
            addCriterion("quarter <", value, "quarter");
            return (Criteria) this;
        }

        public Criteria andQuarterLessThanOrEqualTo(String value) {
            addCriterion("quarter <=", value, "quarter");
            return (Criteria) this;
        }

        public Criteria andQuarterLike(String value) {
            addCriterion("quarter like", value, "quarter");
            return (Criteria) this;
        }

        public Criteria andQuarterNotLike(String value) {
            addCriterion("quarter not like", value, "quarter");
            return (Criteria) this;
        }

        public Criteria andQuarterIn(List<String> values) {
            addCriterion("quarter in", values, "quarter");
            return (Criteria) this;
        }

        public Criteria andQuarterNotIn(List<String> values) {
            addCriterion("quarter not in", values, "quarter");
            return (Criteria) this;
        }

        public Criteria andQuarterBetween(String value1, String value2) {
            addCriterion("quarter between", value1, value2, "quarter");
            return (Criteria) this;
        }

        public Criteria andQuarterNotBetween(String value1, String value2) {
            addCriterion("quarter not between", value1, value2, "quarter");
            return (Criteria) this;
        }

        public Criteria andModularIsNull() {
            addCriterion("modular is null");
            return (Criteria) this;
        }

        public Criteria andModularIsNotNull() {
            addCriterion("modular is not null");
            return (Criteria) this;
        }

        public Criteria andModularEqualTo(String value) {
            addCriterion("modular =", value, "modular");
            return (Criteria) this;
        }

        public Criteria andModularNotEqualTo(String value) {
            addCriterion("modular <>", value, "modular");
            return (Criteria) this;
        }

        public Criteria andModularGreaterThan(String value) {
            addCriterion("modular >", value, "modular");
            return (Criteria) this;
        }

        public Criteria andModularGreaterThanOrEqualTo(String value) {
            addCriterion("modular >=", value, "modular");
            return (Criteria) this;
        }

        public Criteria andModularLessThan(String value) {
            addCriterion("modular <", value, "modular");
            return (Criteria) this;
        }

        public Criteria andModularLessThanOrEqualTo(String value) {
            addCriterion("modular <=", value, "modular");
            return (Criteria) this;
        }

        public Criteria andModularLike(String value) {
            addCriterion("modular like", value, "modular");
            return (Criteria) this;
        }

        public Criteria andModularNotLike(String value) {
            addCriterion("modular not like", value, "modular");
            return (Criteria) this;
        }

        public Criteria andModularIn(List<String> values) {
            addCriterion("modular in", values, "modular");
            return (Criteria) this;
        }

        public Criteria andModularNotIn(List<String> values) {
            addCriterion("modular not in", values, "modular");
            return (Criteria) this;
        }

        public Criteria andModularBetween(String value1, String value2) {
            addCriterion("modular between", value1, value2, "modular");
            return (Criteria) this;
        }

        public Criteria andModularNotBetween(String value1, String value2) {
            addCriterion("modular not between", value1, value2, "modular");
            return (Criteria) this;
        }

        public Criteria andOaIsNull() {
            addCriterion("oa is null");
            return (Criteria) this;
        }

        public Criteria andOaIsNotNull() {
            addCriterion("oa is not null");
            return (Criteria) this;
        }

        public Criteria andOaEqualTo(String value) {
            addCriterion("oa =", value, "oa");
            return (Criteria) this;
        }

        public Criteria andOaNotEqualTo(String value) {
            addCriterion("oa <>", value, "oa");
            return (Criteria) this;
        }

        public Criteria andOaGreaterThan(String value) {
            addCriterion("oa >", value, "oa");
            return (Criteria) this;
        }

        public Criteria andOaGreaterThanOrEqualTo(String value) {
            addCriterion("oa >=", value, "oa");
            return (Criteria) this;
        }

        public Criteria andOaLessThan(String value) {
            addCriterion("oa <", value, "oa");
            return (Criteria) this;
        }

        public Criteria andOaLessThanOrEqualTo(String value) {
            addCriterion("oa <=", value, "oa");
            return (Criteria) this;
        }

        public Criteria andOaLike(String value) {
            addCriterion("oa like", value, "oa");
            return (Criteria) this;
        }

        public Criteria andOaNotLike(String value) {
            addCriterion("oa not like", value, "oa");
            return (Criteria) this;
        }

        public Criteria andOaIn(List<String> values) {
            addCriterion("oa in", values, "oa");
            return (Criteria) this;
        }

        public Criteria andOaNotIn(List<String> values) {
            addCriterion("oa not in", values, "oa");
            return (Criteria) this;
        }

        public Criteria andOaBetween(String value1, String value2) {
            addCriterion("oa between", value1, value2, "oa");
            return (Criteria) this;
        }

        public Criteria andOaNotBetween(String value1, String value2) {
            addCriterion("oa not between", value1, value2, "oa");
            return (Criteria) this;
        }

        public Criteria andSeqIsNull() {
            addCriterion("seq is null");
            return (Criteria) this;
        }

        public Criteria andSeqIsNotNull() {
            addCriterion("seq is not null");
            return (Criteria) this;
        }

        public Criteria andSeqEqualTo(String value) {
            addCriterion("seq =", value, "seq");
            return (Criteria) this;
        }

        public Criteria andSeqNotEqualTo(String value) {
            addCriterion("seq <>", value, "seq");
            return (Criteria) this;
        }

        public Criteria andSeqGreaterThan(String value) {
            addCriterion("seq >", value, "seq");
            return (Criteria) this;
        }

        public Criteria andSeqGreaterThanOrEqualTo(String value) {
            addCriterion("seq >=", value, "seq");
            return (Criteria) this;
        }

        public Criteria andSeqLessThan(String value) {
            addCriterion("seq <", value, "seq");
            return (Criteria) this;
        }

        public Criteria andSeqLessThanOrEqualTo(String value) {
            addCriterion("seq <=", value, "seq");
            return (Criteria) this;
        }

        public Criteria andSeqLike(String value) {
            addCriterion("seq like", value, "seq");
            return (Criteria) this;
        }

        public Criteria andSeqNotLike(String value) {
            addCriterion("seq not like", value, "seq");
            return (Criteria) this;
        }

        public Criteria andSeqIn(List<String> values) {
            addCriterion("seq in", values, "seq");
            return (Criteria) this;
        }

        public Criteria andSeqNotIn(List<String> values) {
            addCriterion("seq not in", values, "seq");
            return (Criteria) this;
        }

        public Criteria andSeqBetween(String value1, String value2) {
            addCriterion("seq between", value1, value2, "seq");
            return (Criteria) this;
        }

        public Criteria andSeqNotBetween(String value1, String value2) {
            addCriterion("seq not between", value1, value2, "seq");
            return (Criteria) this;
        }

        public Criteria andSeqNameIsNull() {
            addCriterion("seqname is null");
            return (Criteria) this;
        }

        public Criteria andSeqNameIsNotNull() {
            addCriterion("seqname is not null");
            return (Criteria) this;
        }

        public Criteria andSeqNameEqualTo(String value) {
            addCriterion("seqname =", value, "seqName");
            return (Criteria) this;
        }

        public Criteria andSeqNameNotEqualTo(String value) {
            addCriterion("seqname <>", value, "seqName");
            return (Criteria) this;
        }

        public Criteria andSeqNameGreaterThan(String value) {
            addCriterion("seqname >", value, "seqName");
            return (Criteria) this;
        }

        public Criteria andSeqNameGreaterThanOrEqualTo(String value) {
            addCriterion("seqname >=", value, "seqName");
            return (Criteria) this;
        }

        public Criteria andSeqNameLessThan(String value) {
            addCriterion("seqname <", value, "seqName");
            return (Criteria) this;
        }

        public Criteria andSeqNameLessThanOrEqualTo(String value) {
            addCriterion("seqname <=", value, "seqName");
            return (Criteria) this;
        }

        public Criteria andSeqNameLike(String value) {
            addCriterion("seqname like", value, "seqName");
            return (Criteria) this;
        }

        public Criteria andSeqNameNotLike(String value) {
            addCriterion("seqname not like", value, "seqName");
            return (Criteria) this;
        }

        public Criteria andSeqNameIn(List<String> values) {
            addCriterion("seqname in", values, "seqName");
            return (Criteria) this;
        }

        public Criteria andSeqNameNotIn(List<String> values) {
            addCriterion("seqname not in", values, "seqName");
            return (Criteria) this;
        }

        public Criteria andSeqNameBetween(String value1, String value2) {
            addCriterion("seqname between", value1, value2, "seqName");
            return (Criteria) this;
        }

        public Criteria andSeqNameNotBetween(String value1, String value2) {
            addCriterion("seqname not between", value1, value2, "seqName");
            return (Criteria) this;
        }

        public Criteria andAnalystIsNull() {
            addCriterion("analyst is null");
            return (Criteria) this;
        }

        public Criteria andAnalystIsNotNull() {
            addCriterion("analyst is not null");
            return (Criteria) this;
        }

        public Criteria andAnalystEqualTo(String value) {
            addCriterion("analyst =", value, "analyst");
            return (Criteria) this;
        }

        public Criteria andAnalystNotEqualTo(String value) {
            addCriterion("analyst <>", value, "analyst");
            return (Criteria) this;
        }

        public Criteria andAnalystGreaterThan(String value) {
            addCriterion("analyst >", value, "analyst");
            return (Criteria) this;
        }

        public Criteria andAnalystGreaterThanOrEqualTo(String value) {
            addCriterion("analyst >=", value, "analyst");
            return (Criteria) this;
        }

        public Criteria andAnalystLessThan(String value) {
            addCriterion("analyst <", value, "analyst");
            return (Criteria) this;
        }

        public Criteria andAnalystLessThanOrEqualTo(String value) {
            addCriterion("analyst <=", value, "analyst");
            return (Criteria) this;
        }

        public Criteria andAnalystLike(String value) {
            addCriterion("analyst like", value, "analyst");
            return (Criteria) this;
        }

        public Criteria andAnalystNotLike(String value) {
            addCriterion("analyst not like", value, "analyst");
            return (Criteria) this;
        }

        public Criteria andAnalystIn(List<String> values) {
            addCriterion("analyst in", values, "analyst");
            return (Criteria) this;
        }

        public Criteria andAnalystNotIn(List<String> values) {
            addCriterion("analyst not in", values, "analyst");
            return (Criteria) this;
        }

        public Criteria andAnalystBetween(String value1, String value2) {
            addCriterion("analyst between", value1, value2, "analyst");
            return (Criteria) this;
        }

        public Criteria andAnalystNotBetween(String value1, String value2) {
            addCriterion("analyst not between", value1, value2, "analyst");
            return (Criteria) this;
        }

        public Criteria andAnalyStartIsNull() {
            addCriterion("analystart is null");
            return (Criteria) this;
        }

        public Criteria andAnalyStartIsNotNull() {
            addCriterion("analystart is not null");
            return (Criteria) this;
        }

        public Criteria andAnalyStartEqualTo(Date value) {
            addCriterionForJDBCDate("analystart =", value, "analyStart");
            return (Criteria) this;
        }

        public Criteria andAnalyStartNotEqualTo(Date value) {
            addCriterionForJDBCDate("analystart <>", value, "analyStart");
            return (Criteria) this;
        }

        public Criteria andAnalyStartGreaterThan(Date value) {
            addCriterionForJDBCDate("analystart >", value, "analyStart");
            return (Criteria) this;
        }

        public Criteria andAnalyStartGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("analystart >=", value, "analyStart");
            return (Criteria) this;
        }

        public Criteria andAnalyStartLessThan(Date value) {
            addCriterionForJDBCDate("analystart <", value, "analyStart");
            return (Criteria) this;
        }

        public Criteria andAnalyStartLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("analystart <=", value, "analyStart");
            return (Criteria) this;
        }

        public Criteria andAnalyStartIn(List<Date> values) {
            addCriterionForJDBCDate("analystart in", values, "analyStart");
            return (Criteria) this;
        }

        public Criteria andAnalyStartNotIn(List<Date> values) {
            addCriterionForJDBCDate("analystart not in", values, "analyStart");
            return (Criteria) this;
        }

        public Criteria andAnalyStartBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("analystart between", value1, value2, "analyStart");
            return (Criteria) this;
        }

        public Criteria andAnalyStartNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("analystart not between", value1, value2, "analyStart");
            return (Criteria) this;
        }

        public Criteria andAnalyEndIsNull() {
            addCriterion("analyend is null");
            return (Criteria) this;
        }

        public Criteria andAnalyEndIsNotNull() {
            addCriterion("analyend is not null");
            return (Criteria) this;
        }

        public Criteria andAnalyEndEqualTo(Date value) {
            addCriterionForJDBCDate("analyend =", value, "analyEnd");
            return (Criteria) this;
        }

        public Criteria andAnalyEndNotEqualTo(Date value) {
            addCriterionForJDBCDate("analyend <>", value, "analyEnd");
            return (Criteria) this;
        }

        public Criteria andAnalyEndGreaterThan(Date value) {
            addCriterionForJDBCDate("analyend >", value, "analyEnd");
            return (Criteria) this;
        }

        public Criteria andAnalyEndGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("analyend >=", value, "analyEnd");
            return (Criteria) this;
        }

        public Criteria andAnalyEndLessThan(Date value) {
            addCriterionForJDBCDate("analyend <", value, "analyEnd");
            return (Criteria) this;
        }

        public Criteria andAnalyEndLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("analyend <=", value, "analyEnd");
            return (Criteria) this;
        }

        public Criteria andAnalyEndIn(List<Date> values) {
            addCriterionForJDBCDate("analyend in", values, "analyEnd");
            return (Criteria) this;
        }

        public Criteria andAnalyEndNotIn(List<Date> values) {
            addCriterionForJDBCDate("analyend not in", values, "analyEnd");
            return (Criteria) this;
        }

        public Criteria andAnalyEndBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("analyend between", value1, value2, "analyEnd");
            return (Criteria) this;
        }

        public Criteria andAnalyEndNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("analyend not between", value1, value2, "analyEnd");
            return (Criteria) this;
        }

        public Criteria andDeveloperIsNull() {
            addCriterion("developer is null");
            return (Criteria) this;
        }

        public Criteria andDeveloperIsNotNull() {
            addCriterion("developer is not null");
            return (Criteria) this;
        }

        public Criteria andDeveloperEqualTo(String value) {
            addCriterion("developer =", value, "developer");
            return (Criteria) this;
        }

        public Criteria andDeveloperNotEqualTo(String value) {
            addCriterion("developer <>", value, "developer");
            return (Criteria) this;
        }

        public Criteria andDeveloperGreaterThan(String value) {
            addCriterion("developer >", value, "developer");
            return (Criteria) this;
        }

        public Criteria andDeveloperGreaterThanOrEqualTo(String value) {
            addCriterion("developer >=", value, "developer");
            return (Criteria) this;
        }

        public Criteria andDeveloperLessThan(String value) {
            addCriterion("developer <", value, "developer");
            return (Criteria) this;
        }

        public Criteria andDeveloperLessThanOrEqualTo(String value) {
            addCriterion("developer <=", value, "developer");
            return (Criteria) this;
        }

        public Criteria andDeveloperLike(String value) {
            addCriterion("developer like", value, "developer");
            return (Criteria) this;
        }

        public Criteria andDeveloperNotLike(String value) {
            addCriterion("developer not like", value, "developer");
            return (Criteria) this;
        }

        public Criteria andDeveloperIn(List<String> values) {
            addCriterion("developer in", values, "developer");
            return (Criteria) this;
        }

        public Criteria andDeveloperNotIn(List<String> values) {
            addCriterion("developer not in", values, "developer");
            return (Criteria) this;
        }

        public Criteria andDeveloperBetween(String value1, String value2) {
            addCriterion("developer between", value1, value2, "developer");
            return (Criteria) this;
        }

        public Criteria andDeveloperNotBetween(String value1, String value2) {
            addCriterion("developer not between", value1, value2, "developer");
            return (Criteria) this;
        }

        public Criteria andDeveloperStartIsNull() {
            addCriterion("developerstart is null");
            return (Criteria) this;
        }

        public Criteria andDeveloperStartIsNotNull() {
            addCriterion("developerstart is not null");
            return (Criteria) this;
        }

        public Criteria andDeveloperStartEqualTo(Date value) {
            addCriterionForJDBCDate("developerstart =", value, "developerStart");
            return (Criteria) this;
        }

        public Criteria andDeveloperStartNotEqualTo(Date value) {
            addCriterionForJDBCDate("developerstart <>", value, "developerStart");
            return (Criteria) this;
        }

        public Criteria andDeveloperStartGreaterThan(Date value) {
            addCriterionForJDBCDate("developerstart >", value, "developerStart");
            return (Criteria) this;
        }

        public Criteria andDeveloperStartGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("developerstart >=", value, "developerStart");
            return (Criteria) this;
        }

        public Criteria andDeveloperStartLessThan(Date value) {
            addCriterionForJDBCDate("developerstart <", value, "developerStart");
            return (Criteria) this;
        }

        public Criteria andDeveloperStartLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("developerstart <=", value, "developerStart");
            return (Criteria) this;
        }

        public Criteria andDeveloperStartIn(List<Date> values) {
            addCriterionForJDBCDate("developerstart in", values, "developerStart");
            return (Criteria) this;
        }

        public Criteria andDeveloperStartNotIn(List<Date> values) {
            addCriterionForJDBCDate("developerstart not in", values, "developerStart");
            return (Criteria) this;
        }

        public Criteria andDeveloperStartBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("developerstart between", value1, value2, "developerStart");
            return (Criteria) this;
        }

        public Criteria andDeveloperStartNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("developerstart not between", value1, value2, "developerStart");
            return (Criteria) this;
        }

        public Criteria andDeveloperEndIsNull() {
            addCriterion("developerend is null");
            return (Criteria) this;
        }

        public Criteria andDeveloperEndIsNotNull() {
            addCriterion("developerend is not null");
            return (Criteria) this;
        }

        public Criteria andDeveloperEndEqualTo(Date value) {
            addCriterionForJDBCDate("developerend =", value, "developerEnd");
            return (Criteria) this;
        }

        public Criteria andDeveloperEndNotEqualTo(Date value) {
            addCriterionForJDBCDate("developerend <>", value, "developerEnd");
            return (Criteria) this;
        }

        public Criteria andDeveloperEndGreaterThan(Date value) {
            addCriterionForJDBCDate("developerend >", value, "developerEnd");
            return (Criteria) this;
        }

        public Criteria andDeveloperEndGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("developerend >=", value, "developerEnd");
            return (Criteria) this;
        }

        public Criteria andDeveloperEndLessThan(Date value) {
            addCriterionForJDBCDate("developerend <", value, "developerEnd");
            return (Criteria) this;
        }

        public Criteria andDeveloperEndLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("developerend <=", value, "developerEnd");
            return (Criteria) this;
        }

        public Criteria andDeveloperEndIn(List<Date> values) {
            addCriterionForJDBCDate("developerend in", values, "developerEnd");
            return (Criteria) this;
        }

        public Criteria andDeveloperEndNotIn(List<Date> values) {
            addCriterionForJDBCDate("developerend not in", values, "developerEnd");
            return (Criteria) this;
        }

        public Criteria andDeveloperEndBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("developerend between", value1, value2, "developerEnd");
            return (Criteria) this;
        }

        public Criteria andDeveloperEndNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("developerend not between", value1, value2, "developerEnd");
            return (Criteria) this;
        }

        public Criteria andChangeFlagIsNull() {
            addCriterion("changeflag is null");
            return (Criteria) this;
        }

        public Criteria andChangeFlagIsNotNull() {
            addCriterion("changeflag is not null");
            return (Criteria) this;
        }

        public Criteria andChangeFlagEqualTo(String value) {
            addCriterion("changeflag =", value, "changeFlag");
            return (Criteria) this;
        }

        public Criteria andChangeFlagNotEqualTo(String value) {
            addCriterion("changeflag <>", value, "changeFlag");
            return (Criteria) this;
        }

        public Criteria andChangeFlagGreaterThan(String value) {
            addCriterion("changeflag >", value, "changeFlag");
            return (Criteria) this;
        }

        public Criteria andChangeFlagGreaterThanOrEqualTo(String value) {
            addCriterion("changeflag >=", value, "changeFlag");
            return (Criteria) this;
        }

        public Criteria andChangeFlagLessThan(String value) {
            addCriterion("changeflag <", value, "changeFlag");
            return (Criteria) this;
        }

        public Criteria andChangeFlagLessThanOrEqualTo(String value) {
            addCriterion("changeflag <=", value, "changeFlag");
            return (Criteria) this;
        }

        public Criteria andChangeFlagLike(String value) {
            addCriterion("changeflag like", value, "changeFlag");
            return (Criteria) this;
        }

        public Criteria andChangeFlagNotLike(String value) {
            addCriterion("changeflag not like", value, "changeFlag");
            return (Criteria) this;
        }

        public Criteria andChangeFlagIn(List<String> values) {
            addCriterion("changeflag in", values, "changeFlag");
            return (Criteria) this;
        }

        public Criteria andChangeFlagNotIn(List<String> values) {
            addCriterion("changeflag not in", values, "changeFlag");
            return (Criteria) this;
        }

        public Criteria andChangeFlagBetween(String value1, String value2) {
            addCriterion("changeflag between", value1, value2, "changeFlag");
            return (Criteria) this;
        }

        public Criteria andChangeFlagNotBetween(String value1, String value2) {
            addCriterion("changeflag not between", value1, value2, "changeFlag");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("remark is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("remark is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("remark =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("remark <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("remark >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("remark >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("remark <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("remark <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("remark like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("remark not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("remark in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("remark not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("remark between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("remark not between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andOperatorIsNull() {
            addCriterion("operator is null");
            return (Criteria) this;
        }

        public Criteria andOperatorIsNotNull() {
            addCriterion("operator is not null");
            return (Criteria) this;
        }

        public Criteria andOperatorEqualTo(String value) {
            addCriterion("operator =", value, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorNotEqualTo(String value) {
            addCriterion("operator <>", value, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorGreaterThan(String value) {
            addCriterion("operator >", value, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorGreaterThanOrEqualTo(String value) {
            addCriterion("operator >=", value, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorLessThan(String value) {
            addCriterion("operator <", value, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorLessThanOrEqualTo(String value) {
            addCriterion("operator <=", value, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorLike(String value) {
            addCriterion("operator like", value, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorNotLike(String value) {
            addCriterion("operator not like", value, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorIn(List<String> values) {
            addCriterion("operator in", values, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorNotIn(List<String> values) {
            addCriterion("operator not in", values, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorBetween(String value1, String value2) {
            addCriterion("operator between", value1, value2, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorNotBetween(String value1, String value2) {
            addCriterion("operator not between", value1, value2, "operator");
            return (Criteria) this;
        }

        public Criteria andChangeDateIsNull() {
            addCriterion("changedate is null");
            return (Criteria) this;
        }

        public Criteria andChangeDateIsNotNull() {
            addCriterion("changedate is not null");
            return (Criteria) this;
        }

        public Criteria andChangeDateEqualTo(Date value) {
            addCriterionForJDBCDate("changedate =", value, "changeDate");
            return (Criteria) this;
        }

        public Criteria andChangeDateNotEqualTo(Date value) {
            addCriterionForJDBCDate("changedate <>", value, "changeDate");
            return (Criteria) this;
        }

        public Criteria andChangeDateGreaterThan(Date value) {
            addCriterionForJDBCDate("changedate >", value, "changeDate");
            return (Criteria) this;
        }

        public Criteria andChangeDateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("changedate >=", value, "changeDate");
            return (Criteria) this;
        }

        public Criteria andChangeDateLessThan(Date value) {
            addCriterionForJDBCDate("changedate <", value, "changeDate");
            return (Criteria) this;
        }

        public Criteria andChangeDateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("changedate <=", value, "changeDate");
            return (Criteria) this;
        }

        public Criteria andChangeDateIn(List<Date> values) {
            addCriterionForJDBCDate("changedate in", values, "changeDate");
            return (Criteria) this;
        }

        public Criteria andChangeDateNotIn(List<Date> values) {
            addCriterionForJDBCDate("changedate not in", values, "changeDate");
            return (Criteria) this;
        }

        public Criteria andChangeDateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("changedate between", value1, value2, "changeDate");
            return (Criteria) this;
        }

        public Criteria andChangeDateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("changedate not between", value1, value2, "changeDate");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table outplan
     *
     * @mbggenerated do_not_delete_during_merge Tue May 30 13:30:43 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table outplan
     *
     * @mbggenerated Tue May 30 13:30:43 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}