package com.sinosoft.planb.db.entity;

public class RoleMenu {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rolemenu.rolecode
     *
     * @mbggenerated Thu May 25 19:32:37 CST 2017
     */
    private Integer roleCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rolemenu.menucode
     *
     * @mbggenerated Thu May 25 19:32:37 CST 2017
     */
    private Integer menuCode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rolemenu.rolecode
     *
     * @return the value of rolemenu.rolecode
     *
     * @mbggenerated Thu May 25 19:32:37 CST 2017
     */
    public Integer getRoleCode() {
        return roleCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rolemenu.rolecode
     *
     * @param roleCode the value for rolemenu.rolecode
     *
     * @mbggenerated Thu May 25 19:32:37 CST 2017
     */
    public void setRoleCode(Integer roleCode) {
        this.roleCode = roleCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rolemenu.menucode
     *
     * @return the value of rolemenu.menucode
     *
     * @mbggenerated Thu May 25 19:32:37 CST 2017
     */
    public Integer getMenuCode() {
        return menuCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rolemenu.menucode
     *
     * @param menuCode the value for rolemenu.menucode
     *
     * @mbggenerated Thu May 25 19:32:37 CST 2017
     */
    public void setMenuCode(Integer menuCode) {
        this.menuCode = menuCode;
    }
}