package com.sinosoft.planb.db.entity;

public class UserRole {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userrole.usercode
     *
     * @mbggenerated Thu May 25 19:32:37 CST 2017
     */
    private String userCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userrole.rolecode
     *
     * @mbggenerated Thu May 25 19:32:37 CST 2017
     */
    private Integer roleCode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userrole.usercode
     *
     * @return the value of userrole.usercode
     *
     * @mbggenerated Thu May 25 19:32:37 CST 2017
     */
    public String getUserCode() {
        return userCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userrole.usercode
     *
     * @param userCode the value for userrole.usercode
     *
     * @mbggenerated Thu May 25 19:32:37 CST 2017
     */
    public void setUserCode(String userCode) {
        this.userCode = userCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userrole.rolecode
     *
     * @return the value of userrole.rolecode
     *
     * @mbggenerated Thu May 25 19:32:37 CST 2017
     */
    public Integer getRoleCode() {
        return roleCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userrole.rolecode
     *
     * @param roleCode the value for userrole.rolecode
     *
     * @mbggenerated Thu May 25 19:32:37 CST 2017
     */
    public void setRoleCode(Integer roleCode) {
        this.roleCode = roleCode;
    }
}