package com.sinosoft.planb.db.mapper;

import com.sinosoft.planb.db.entity.RoleMenu;
import com.sinosoft.planb.db.entity.RoleMenuExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RoleMenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rolemenu
     *
     * @mbggenerated Thu May 25 19:32:37 CST 2017
     */
    int countByExample(RoleMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rolemenu
     *
     * @mbggenerated Thu May 25 19:32:37 CST 2017
     */
    int deleteByExample(RoleMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rolemenu
     *
     * @mbggenerated Thu May 25 19:32:37 CST 2017
     */
    int insert(RoleMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rolemenu
     *
     * @mbggenerated Thu May 25 19:32:37 CST 2017
     */
    int insertSelective(RoleMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rolemenu
     *
     * @mbggenerated Thu May 25 19:32:37 CST 2017
     */
    List<RoleMenu> selectByExample(RoleMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rolemenu
     *
     * @mbggenerated Thu May 25 19:32:37 CST 2017
     */
    int updateByExampleSelective(@Param("record") RoleMenu record, @Param("example") RoleMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rolemenu
     *
     * @mbggenerated Thu May 25 19:32:37 CST 2017
     */
    int updateByExample(@Param("record") RoleMenu record, @Param("example") RoleMenuExample example);
}